### ISSUE TITLE
Entscheiden der Regeln für die Sprache im Code, in Commits und auf GitHub

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#1]
Für dieses Projekt ([BBFW-Project](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md "Link zur README des Projektes")) sollen festgelegte Regeln für die Sprache gelten, die dann von allen Mitwirkenden einzuhalten sind. Dies soll chaotisches Durcheinander vermeiden.

Die Regeln für die Sprache werden von dem obersten Zirkel des Projektteams bestimmt.

Für verschiedene Umgebungen können auch verschiedene Sprachen möglich sein. Folgende Unterscheidungen sind möglich zu welchen eine Entscheidung zu treffen ist:

1. **Code** mit all seinen Bestandteilen (Klassen, Variablennamen, Testnamen, Kommentare) ist festgelegt auf die Sprache **Englisch**. Hierüber kann nicht entschieden werden.
1. **Commits** beziehungsweise deren Beschreibung (sowohl beim lokalen Committen als auch Merge-Commits auf GitHub)
1. **GitHub:** mit den verschiedenen Bestandteilen wie Kommentare, Beschreibungen von Issues und PullRequests sowie Milestones

##### Nachträgliche Erweiterung der Issue:
* Die Entscheidung ist in der [README](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md "Link zur README des Projektes") zu dokumentieren.

**Comment by RF-Buerky** [comment]
Mein Vorschlag für die Sprachregeln:

**Zu 2: Sprache Deutsch**
Würde die Commits gerne in Deutsch machen. Dies fällt mir leichter als englisch. Auf GitHub schlage ich auch Deutsch vor und da Merge-Commits auf GitHub vorgenommen werden, finde ich es passend die Commits auch in Deutsch zu machen.

**Zu 3: Sprache Deutsch**
Alles auf GitHub würde ich gerne auch aus Gründen der Einfachheit in Deutsch machen.

**Comment by FelixWerle** [comment]
**Zu 2: Sprache Deutsch oder Englisch**
Würde mich anschließen die Commits in Deutsch zu machen, hätte aber auch kein großes Problem damit die Beschreibungen in Englisch durchzuführen, da diese oft noch recht einfach gestaltet sind.

**Zu 3: Sprache Deutsch**
Aufgrund der höheren Komplexität wurde ich das auch gerne deutsch halten, da es für mich so verständlicher, einfacherer und schneller geht.

**Comment by jwustmann** [comment]
Ich schließe mich dem Vorschlag von RF-Buerky an, 2 und 3 auf deutsch, der Einfachheit und Verständlichkeit halber.
Dies sollte der Mehrheitsentscheid sein

**Comment by RF-Buerky** [comment]
Der vierte im Bunde, [dbaumy](https://github.com/dbaumy "Link zu Profil von dbaumy"), hat sich über ein anderes Kommunikationsmedium auch für Deutsch ausgesprochen. Er kann gerade nicht auf GitHub, daher seine Rückmeldung auf Umwegen.

**Comment by RF-Buerky** [comment]
Es wurde sich entschieden zu:

1. **Code** mit all seinen Bestandteilen (Klassen, Variablennamen, Testnamen, Kommentare) **auf Englisch**. 
1. **Commits** beziehungsweise deren Beschreibung (sowohl beim lokalen Committen als auch Merge-Commits auf GitHub) **auf Deutsch**
1. **GitHub**: mit den verschiedenen Bestandteilen wie Kommentare, Beschreibungen von Issues und PullRequests sowie Milestones **auf Deutsch**

Die Entscheidung ist in der [README](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md "Link zur README") festzuhalten. Es wird dafür eine Issue erstellt werden.

**Comment by nipafx** [comment]
Vorbildlich gelöst. :smiley: Es spricht aber nichts dagegen die Besprechung einer Lösung **und** die Umsetzung im gleichen Issue zu machen (ist sogar üblich). Wenn ihr möchtet, könnt ihr dieses Issue also wieder öffnen und zur Dokumentation der Entscheidung weiterverwenden.

**Comment by RF-Buerky** [comment]
Ok dann wird das gemacht. 

Also dann nun die Erweiterung der Issue: Entscheidung in der README festhalten.

Diese Erweiterung der Issue wird als Nachtrag in der Issue-Beschreibung am Anfang angefügt.

**Comment by RF-Buerky** [comment]
Festhalten der Entscheidung erfolgreicht gelößt durch PullRequest #2

**Comment by RF-Buerky** [comment]
Festhalten der Entscheidung erfolgreicht gelößt durch PullRequest #2
