### ISSUE TITLE
Integration mittels Travis

### ISSUE THREAD

**Issue by FelixWerle** [RF-Buerky/BBFW-Project#10]
Hierfür sollen wir uns nach der Konfiguration von Maven an Herr Parlog wenden.

**Comment by RF-Buerky** [comment]
Für den Release ist diese Issue hier nicht Einfluss nehmen, richtig? Heißt man kann den Release nun machen?

@nicolaiparlog

**Comment by nipafx** [comment]
Ok... Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das wohl nachher konfigurieren (hoffentlich), aber anschmeißen muss es @RF-Buerky.

Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen. Ich bereite solange schonmal die `.travis.yml` vor.

**Comment by RF-Buerky** [comment]
Hab versucht 2 und 3 zu machen. Könnte funktioniert haben.

**Comment by nipafx** [comment]
Super, läuft! Kann geschlossen werden, wenn #39 gemergt ist.

**Comment by RF-Buerky** [comment]
Gelößt durch gemergten PullRequest #39
