### ISSUE TITLE
Fehler in Funktion getDelayedAtHour ?

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#102]
Vielleicht haben wir einen Fehler in der Funktion `getDelayedAtHour`. Die Funktion ist in dem Interface Vehicle.

Die Funktion lautet aktuell:
```kotlin
    override fun getDelayedAtHour(timestep: Int) {
        // if the vehicle wanted to drive, its delay increased
        // (otherwise it just waited an hour, not reducing its delay)
        if (wannaDriveInHours.contains(timestep)) {
            delay += 1
            this.gotNewDelayInHours.add(timestep)
            this.gotNewDelayInHours.sort()
        }
    }
```

Ein Fahrzeug kann demnach nur eine zusätzliche Verspätung bekommen, wenn der `timestep` in der Liste `wannaDriveInHours` drin ist.

Ich fände es logisch, wenn ein Fahrzeug auch dann eine zusätzliche Verspätung bekommen kann, wenn es noch fährt um Verspätungen aus vergangenen `timesteps` auszugleichen.

Daher würde ich noch ein "oder delay > 0" einfügen, also so:
```kotlin
    override fun getDelayedAtHour(timestep: Int) {
        // if the vehicle wanted to drive, its delay increased
        // (otherwise it just waited an hour, not reducing its delay)
        if (wannaDriveInHours.contains(timestep) || delay > 0 ) {
            delay += 1
            this.gotNewDelayInHours.add(timestep)
            this.gotNewDelayInHours.sort()
        }
    }
```

Andererseits kann dies wieder zu Verwirrung führen da dann in den Results Stunden als verspätet gelistet werden, indenen man ursprünglich garnicht vorhatte zu fahren. Hier kommt wieder die Problematik mit der philosphischen Betrachtung, was genau als delayed in der Ausgabe drin stehen soll. (@nicolaiparlog )

**Comment by jwustmann** [comment]
Wenn ich das richtig sehe, würde dein Entwurf so wie er da steht einen ewigen Stau für das Fahrzeug bedeuten sobald es einmal verspätet wurde, denn sobald ein delay größer 0 ist erhöht es sich im nächsten Zeitschritt automatisch, da die Bedingung erfüllt ist oder irre ich mich da ?


 

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nipafx** [comment]
Den Namen `delay` habe ich vielleicht nicht geschickt gewählt ([naming is hard](https://martinfowler.com/bliki/TwoHardThings.html)). Wenn man schon eine Stunde zu spät zum Kaffeetrinken bei Oma ist und dann noch ne Stunde im Stau steht, ist man natürlich zwei Stunden zu spät.

Die Variable hält aber fest, wie viele Stunden man noch fahren muss, bis man seine gewünschte Strecke abgefahren hat. Wenn du eine Stunde zu Oma fahren musst und erstmal zwei Stunden im Stau stehst, muss du immer noch nur eine Stunde fahren, nicht drei.

:bulb: Wenn du glaubst, das Programm verhält sich falsch, versuch einen Test zu schreiben, der _wegen des falschen Verhaltens_ scheitert. Dann kann man am besten sehen, was du meinst.

**Comment by RF-Buerky** [comment]
Okay dann stimmt ja alles. Kam gerade auch nicht auf einen besseren Namen als `delay`. Ewig lange Namen wie `hoursMoreToDriveCauseOfDelay` ist vielleicht nicht so idael. Oder wie ist da die allgemeine Regel? @nicolaiparlog

**Comment by nipafx** [comment]
Was ist mit `lag`, ist das auch zu lang? 😜 Kürzere Namen sind schon besser, aber wie man Ausdrucksstärke gegen Länge abwiegt, ist nicht allgemein zu beantworten.

**Comment by RF-Buerky** [comment]
`lag` ist gut. Ich ändere es und mache einen PullRequest
