### ISSUE TITLE
Zuallerletzt: Überall Reformat Code ausführen

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#104]
Damit der Code beim letzten Release gut anzusehen ist sollte in allen Dateien `Reformat Code` ausgeführt werden.

Diese Issue ist zuallerletzt auszuführen, wenn sonst keine PullRequests mehr anstehen oder auf einen Merge warten.

**Comment by jwustmann** [comment]
Guter Gedanke. In diesem Kontext würde ich auch nochmal prüfen, ob alle Funktionen als solche benannt sind; z.b. randomDelay wäre vielleicht besser delayByChance ?

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RF-Buerky** [comment]
ja kann man auch machen.
