### ISSUE TITLE
Konfiguration von JUnit 4 durch erweitern von 'pom.xml' + schreiben eines kleines Tests 'HelloWorldTest'

### ISSUE THREAD

**Issue by FelixWerle** [RF-Buerky/BBFW-Project#11]
Teste sollen das erwartete Verhalten, sowie die Fehlerfälle des Codes prüfen. Ein Test kann schnell ausgeführt werden, um zu prüfen, ob das Programm noch wie erwartet funktioniert.

JUnit ist eine "library", die es einfacher macht, einen Test zu schreiben. Um einen Test zu ermöglichen, muss unsere vorher in Issue #9 verwendete `pom.xml`  erweitert werden. 

Wir sollen mithilfe eines Testes unser erstelltes "HelloWorld"-Programm überprüfen.

**Comment by RF-Buerky** [comment]
Gelößt durch Issue #35 

@dbaumy Du hattest "Close #11" geschrieben statt "Closes #11". Daher dieser manuelle Close.
