### ISSUE TITLE
Veröffentlichung der Version 1.0

### ISSUE THREAD

**Issue by FelixWerle** [RF-Buerky/BBFW-Project#13]
Wenn man auf dem master Branch eine funktionierende Version hat, sollte man diese als Release festhalten.
Um verschiedene Release Versionen in der Historie unseres Projektes zu markieren werden Tags verwendet (z.B. v1.0, v2.0 ...).

Neue Tags lassen sich mithilfe des Befehls `git tag <tagbezeichnung>` anlegen. In diesem Fall handelt es sich um einen einfachen (lightweight) Tag, welcher nur die jeweilige Commit Historie abspeichert. Fügt man dem Befehl noch ein `-a` hinzu erhält man einen kommentierten (annotated) Tag. Dieser beinhaltet zusätzliche Informationen wie Name und Email-Adresse des Erstellers oder das jeweilige Datum und wird als vollwertiges Objekt in der Git Datenbank gespeichert. 

Wenn man den Befehl `git show` auf einen Tag anwendet, lassen sich diese Informationen anzeigen.  Alle bisher erstellten tags erhält man durch `git tag`.

Beim pushen muss zum mitpushen der Tags extra die Schlüsselbezeichnung `--tag` hinzugefügt werden.

Auf das im Tag gespeicherte Abbild kann man zugreifen, indem ein neuer Branch anhand des Tags erstellt wird: `git checkout -b <branchname> <tagbezeichnung>`.

**Comment by RF-Buerky** [comment]
Vor dem Release ist noch der Hinweis "SNAPSHOT" aus der Zieldatei bei der pom.xml zu entfernen.

... und nach dem Release wieder einfügen.

**Comment by nipafx** [comment]
@RF-Buerky hat schon jede Menge Informationen zusammengetragen - hier nochmal der genaue Ablauf:

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen

Den letzten Schritt hab ich schon lange nicht mehr gemacht, kann sein, dass ihr da ein wenig suchen müsst.

**Comment by RF-Buerky** [comment]
Release wurde beim ersten Versuch von GitHub automatisch gemacht, obwohl der Tag nichtmal auf master war.

**Comment by nipafx** [comment]
Ja, weil man meistens nur `master` zumindest aber nicht auf feature Branches tagt. :wink: Kannst du [hier](https://github.com/RF-Buerky/BBFW-Project/releases/tag/1.0) aber wieder löschen (oben rechts).

**Comment by RF-Buerky** [comment]
Sehe nichts wo man einem Release noch eine Datei anhängen kann. Versuche den Release jetzt einfach mal so, dass die .jar dazu und wieder weg commited wird - wie man das beim `SNAPSHOT`-Anhängsel auch macht.

**Comment by jwustmann** [comment]
habe bisher auch nichts dazu gefunden, was funktioniert hätte. Klingt erstmal vielversprechend für mich

**Comment by nipafx** [comment]
Nein, bitte keine JAR comitten! Ergibt auch keinen Sinn, denn Releases macht man ja für Leute, die nichts mit der Code-Basis am Hut haben.

Wenn das Release da ist, zeige ich euch, wo man die JAR anhängt.

**Comment by RF-Buerky** [comment]
Was soll denn alles im Release drin sein bzw. was nicht? Die pom.xml zum Beispiel auch nicht?

Der Release ist [da](https://github.com/RF-Buerky/BBFW-Project/releases) mit einer .jar. Die wurde leider noch vor dem Kommentar commited.  🎉  💯

**Comment by nipafx** [comment]
Gratulation! 👍 

Wenn du jetzt zu dem Release gehst, da oben rechts auf Edit klickst siehst du das hier:

![attach-binaries](https://user-images.githubusercontent.com/6537432/28945052-36db7a44-78a5-11e7-843c-892c9de473b8.png)

Rate, wo man die JAR anhängen kann. 🤡

**Comment by RF-Buerky** [comment]
Shame 🔔 
🤦‍♂️ 

Also alten Release löschen und neu

Ansonsten war der Inhalt des Release korrekt? Die pom.xml undso bleiben drin?

**Comment by RF-Buerky** [comment]
hmm der hat ja die .jar auch garnicht wieder gelöscht hier im Repository...

**Comment by nipafx** [comment]
Naja, "drin"... aktuell müssten User die von GitHub erstellte ZIP des Repositories runterladen und dann die JAR daraus fummeln. Außerdem müssten sie wissen, dass das so ist.

Häng sie trotzdem mal an.

**Comment by RF-Buerky** [comment]
Die .jar hängt dran

**Comment by nipafx** [comment]
:+1: Meilenstein 1 erledigt. 🎉

**Comment by RF-Buerky** [comment]
Aber die jar war ja nun noch in dem zip-Ordner drin wo sie eig. nicht rein soll.

von mir aus könnte man die letzten zwei commits auf master resetten und den Release nochmal ordentlich machen.

**Comment by jwustmann** [comment]
Oder wir lernen daraus und sind jetzt reich an Erfahrung ("Machen Sie mal, Sie sind nun schließlich Experten...")

**Comment by nipafx** [comment]
Sachen auf Master zu resetten ist fies. Das sollte man nur in Notfällen (und dies ist keiner) machen - mit allem anderen muss man leben.
