### ISSUE TITLE
Aufbau eines einfachen Verkehrsimulationsprogramms für einen Zeitschritt

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#20]
Die Simulation soll aus **mehreren Autos** und **einem Straßennetz** (das nicht in einzelne Straßen ausdifferenziert wird) mit einer gewissen Kapazität bestehen. Jedes Auto weiß, ob und wann es fahren will. In Version 1.0 wird **ein Zeitschritt** (= eine Stunde) betrachtet.

- Das Straßennetz summiert die Anzahl der Autos, die zu einer gegebenen Stunde fahren wollen auf und gleicht den Bedarf mit der eigenen Kapazität ab.
- Ist die Kapazität größer oder gleich dem Bedarf, können alle Autos ungehindert fahren
- ist die Kapazität geringer als Bedarf werden alle Fahrten wegen Staus verzögert
- das Straßennetz entscheidet für jedes Fahrzeug, ob es ungehindert fahren kann oder in einen Stau gerät

**Comment by nipafx** [comment]
Damit das nicht verloren geht: Die Tests für `RoadNetwork` fehlen noch.

**Comment by jwustmann** [comment]
Hier geht nichts verloren; )

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
