### ISSUE TITLE
Fahrtberichtsfunktion für Autos

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#22]
Am Simulationsende soll jedes Auto "wissen" und ausgeben, ob es ungehindert fahren konnte oder in einen Stau geraten ist.

**Comment by jwustmann** [comment]
@RF-Buerky @FelixWerle @dbaumy 

Hier müsste es mal weiter gehen, damit ich beim Parsen des Outputs auch den Fahrbericht mitausgeben kann. Falls sich keiner bis 13 Uhr assigned mache ich das grade mit

**Comment by RF-Buerky** [comment]
Ist vielleicht schon durch #55 ausreichend gelößt.

In Klasse Vehicle.kt

> fun delayed (): Vehicle {
> return Vehicle (id , wannaDrive , true)
> }

Da wurd dann unbewusst diese Issue auch gemacht.

Und Ausgabe des Outputs für in die CSV-Datei steht in der Main bereit 
> val simulationResults : List<Vehicle> = testRoad.scenario(vehiclesInterests)

**Comment by jwustmann** [comment]
Dann ist dieser issue mit #55 bearbeitet
