### ISSUE TITLE
Main Funktion mit CSV-Integration schreiben

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#23]
Schreiben der Main Funktion, die  **_Univocity Parsers_** nutzt, um Autos und ihr Fahrbestreben einzulesen und das Ergebnis (ungestörte Fahrt oder Stau) in einer CSV-Datei auszugeben.
Die bestehende **_scenario_** Funktion soll davon unberührt bleiben.

**Comment by RF-Buerky** [comment]
Wurde Teilweise durch #55 gelößt, zweite Hälfte kommt wird nun mit Issue #57 bearbeitet.

**Comment by jwustmann** [comment]
Arbeite mit PR #58 daran; wenn der mal so weit ist
