### ISSUE TITLE
README  um Anleitung erweitern

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#24]
Die [README Datei](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md) soll um eine Nutzerdokumentation erweitert werden, die es dem Nutzer in erklärender Weise ermöglicht, das Programm zu gebrauchen.

**Comment by RF-Buerky** [comment]
README mach ich gern ^^

**Comment by RF-Buerky** [comment]
Wie soll die Ausführung denn möglich sein, wenn der Ausführende sich keine eigene .jar erstellen soll? Die .jar ist ja Abhängig von dem CSV-Input. @nicolaiparlog 

Denke der Anwender müsste die CSV Datei bearbeiten und seine Vehicles mit den Fahrwünschen angeben. Danach dann selbst eine .jar erstellen und ausführen und schließlich dann in die entstehende results.csv rein gucken.

**Comment by jwustmann** [comment]
Gibt es hier neue Ideen? Mir kam bisher nichts in den Sinn, außer zu versuchen, den Parser eine CSV Datei von einem höheren Ordnerpfad einlesen zu lassen (gibt es die Möglichkeit, dem Programm zu sagen, dass es den Pfad verwenden soll, den die JAR zukünftig einmal haben wird? )

**Comment by RF-Buerky** [comment]
Nichts neues...

Vielleicht muss man @nicolaiparlog mal ne Mail schrieben - kann sein dass diese Frage hier untergeht zwischen all den vielen Mitteilungen die er von GitHub bekommen.

Schreibt jemand? Muss grad ma weg.

**Comment by dbaumy** [comment]
Ich schreibe die Mail ;)

Update:
Die Mail ist raus, ich hatte Nicolai gefragt ob wir das Problem so lösen können, indem wir den Input einfach (simple) vorgeben. (Ihr seid CC-gesetzt)

**Comment by nipafx** [comment]
Ich war out of Internet...

Ja, man könnte einen Parameter einführen, der angibt, von wo die CSV gelesen wird, aber das habe ich nicht vorgesehen, weil es sonst zu viel wird. In der Tat ist diese Aufgabe so etwas komisch. Könnt ihr weglassen (also das Issue schließen).

**Comment by RF-Buerky** [comment]
Gelößt durch PullRequest #74
