### ISSUE TITLE
Version 2.0 veröffentlichen

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#25]
Version 2.0 wird mit allen erweiterten Features veröffentlicht

**Comment by jwustmann** [comment]
Es macht für die Funktionalität zwar keinen Unterschied, aber ich bin dafür in im Parser und allen damit verknüpften Dingen ` val customerRows: MutableList<Array<Any>> = mutableListOf()` abzuändern, da wir keine Kunden haben sondern Fahrzeuge in den Reihen; außer das ganze sollte ursprünglich ` customRows` heißen, weil diese "customized" sind...

Ich mache mal einen PR auf, nur zur optischen Schönung, inhaltlich ändere ich nichts.

**Comment by RF-Buerky** [comment]
Ja ändern. Veilleicht zu `vehiclesRows`.

**Comment by jwustmann** [comment]
Bearbeitet in #70

**Comment by dbaumy** [comment]
Das Grundgerüst für den Text ist in Bearbeitung.
Update: hab ich dir per Mail geschickt @RF-Buerky

**Comment by RF-Buerky** [comment]
Release 2.0 ist draußen 🎉 
Zu finden [hier](https://github.com/RF-Buerky/BBFW-Project/releases)

![grafik](https://user-images.githubusercontent.com/28202401/29039513-d781ba4a-7bab-11e7-84ac-d139690f5180.png)

**Comment by nipafx** [comment]
🎉

**Comment by RF-Buerky** [comment]
Yay, die 4.0 haben wir uns verdient... 😅

**Comment by dbaumy** [comment]
🤸‍♂️
