### ISSUE TITLE
Datei mit Struktur des Projektes erstellen und in README dokumentieren

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#27]
Sich in ein Programm hineinzudenken kann schwierig sein. Daher schlage ich vor, eine Datei zu erstellen die einen Überblick über die Struktur unseres Projektes beinhaltet. Dies soll Mitwirkenden das Hineindenken erleichern. 

Anbieten würde sich zum Beispiel, die values, entities und methods nach dem OOP-Vorbild aufzuführen und ganz kurz zu formulieren was dort jeweils geschieht.

Im späteren Verlauf alle Änderungen auch in diese Datei einzupflegen kann lästig sein. Denke aber nicht dass man da dann so genau sein müsste - für den Überblick ist's ok wenn's nicht immer aktuell und vollständig ist.

Werde einfach mal machen und einen PullRequest erstellen wo ihr dann sagen könnt was ihr meint.

**Comment by jwustmann** [comment]
Zum aktuellen Zeitpunkt würde ich sagen, dass die Anleitung der Readme für Außenstehende genügen muss. Da unsere Gruppe recht übersichtlich ist und ein hohes Aktivitätsniveau hat, ist eigentlich immer ersichtlich (auch anhand der Kommentare hier), wohin die Reise gehen soll. Bei größeren Gruppen oder komplexeren Projekten wäre es als Absichtserklärung oder "Pflichtansatz" wohl nicht verkehrt, hier erhöht eine zu aktualisierende Datei den Arbeitsaufwand. Ich wäre dafür den PR zu schließen.

**Comment by RF-Buerky** [comment]
Naja eine Beschreibugn ist in OLAT gefordert...

**Comment by RF-Buerky** [comment]
Beim Release von 2.0 sollte eine richtige Bechreibung zur Nutzung da sein.

**Comment by jwustmann** [comment]
Schreibst du nicht genau das in #24 ?

**Comment by RF-Buerky** [comment]
Ja, das war zu Release 1.0. Die Anwendung wird ja erweitert und daher muss auch die Beschreibung erweitert werden.

**Comment by RF-Buerky** [comment]
Oh ja sry. War in der Issue verrutscht. 

Finde nun auch dass die Struktur nicht gebraucht wird.

Ich mach die Sache hier dann grad zu und auch meinen PullRequest dazu #28 . @nicolaiparlog sagte ja auch dass das nur gemacht werden soll wenn alle zustimmen. Also wech damit.
