### ISSUE TITLE
README verbessern (Projektbeschreibung, Bearbeiter, ...)

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#3]
Die [README](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md "Link zur README des Projektes") ist noch taufrisch. Ein paar Must-Have-Informationen gehören auf jeden Fall noch in die Datei.

Die Must-Have
* Eine Projektbeschreibung
* Unser Team
* Die Ziele (Anforderungen von [Nicolai](https://github.com/nicolaiparlog "Link zu Profil von Nicolai"))

##### ... offen für weiteren Inhalt für die README.

**Comment by RF-Buerky** [comment]
Issue gelößt durch PullRequest #4

**Comment by nipafx** [comment]
:bulb: Wenn du in der Beschreibung des Pull Requests "Closes #3" schreibst, schließt GitHub automatisch #3, wenn der PR gemergt wird.
