### ISSUE TITLE
.gitignore richtig benennen

### ISSUE THREAD

**Issue by nipafx** [RF-Buerky/BBFW-Project#31]
Ich hab bei #8 / #17 nicht richtig aufgepasst. Damit Git die Datei erkennt und verarbeitet, muss sie `.gitignore` heißen (man beachte die fehlende Dateiendung). Weil die aktuell `.gitignore.txt` heißt, erfüllt sie ihren Zweck nicht.

**Comment by jwustmann** [comment]
@RF-Buerky 
Ich denke es wäre sinnvoll, wenn wir uns für die Bearbeitung eines Issues für diesen auch assignen; wir haben wohl beiden diesen Issue bearbeitet. Das ist in diesem Fall ein Aufwand von 2 Minuten gewesen, aber im weiteren Projektverlauf wäre es doch sehr ärgerlich.

Zur Kenntnisnahme: @dbaumy  @FelixWerle

**Comment by RF-Buerky** [comment]
Ok ja hast recht, werde nun auf die Assigns achten.

Dachte dass die Sache so schnell geht, dass es keine Kollision gibt und dann der Verweis auf den PullRequest reicht.
> This was referenced [...]
>.gitignore.txt verbessert zu .gitignore #32 

(Über der Meldung zu deinem Assign in dieser Issue)

**Comment by nipafx** [comment]
Ja, assignen ist auf jeden Fall wichtig. Schön, dass ihr das durch eigene Erfahrung bestätigen könnt. :smile_cat:
