### ISSUE TITLE
Test-Ordnerstruktur mit Testdatei als Platzhalter erstellen

### ISSUE THREAD

**Issue by dbaumy** [RF-Buerky/BBFW-Project#47]
Damit die Ordnerstruktur für Tests wieder vorhanden ist und GIT nur diese übernimmt ist es nötigt das eine Testdatei vorhanden ist (erstellt wird), da GIT nur Dateien berücksichtigt und nicht (leere) Ordner allein.

**Comment by nipafx** [comment]
:bulb: @dbaumy: Meilenstein nicht vergessen. :smiley:
