### ISSUE TITLE
Issues für Milestone 1 erstellen

### ISSUE THREAD

**Issue by nipafx** [RF-Buerky/BBFW-Project#5]
Bitte erstellt erst alle Issues für Milestone 1 bevor ihr weitere Aufgaben angeht.

**Comment by nipafx** [comment]
By the way, ich hab den Meilensteinen gerade Due Dates verpasst. Die sind relativ willkürlich gewählt, aber dadurch werden sie sinnvoll sortiert.

**Comment by RF-Buerky** [comment]
Die Issues zu Block 1 sind nun grundsätzlich erstellt. Teilweise muss die Beschreibung der Issues noch erfolgen (@FelixWerle).

**Comment by nipafx** [comment]
Ja, sehr gut. Generell kann der Titel ruhig etwas knapper sein (mehr wie ein Punkt auf einer TODO-Liste, z.B. "JUnit 4 verwenden") und dafür der längere Text in die Beschreibung. Das müsst ihr aber jetzt nicht mehr ändern - reicht beim nächsten Mal.

> Teilweise muss die Beschreibung der Issues noch erfolgen

Das sollte spätestens bei Arbeitsbeginn der Fall sein.
