### ISSUE TITLE
Double-Wert in RoadNetworkTest zu Int-Werten machen

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#52]
Wir sind wegen den Rundungsfehlern auf Int-Werte umgestiegen. In der Testklasse [RoadNetworkTest](https://github.com/RF-Buerky/BBFW-Project/blob/code/src/test/kotlin/RoadNetworkTest.kt) sind noch Double-Werte vorhanden. Diese müssen noch zu Int-Werten geändert werden.

**Comment by nipafx** [comment]
In diesem Issue versteckt sich eine wichtige Lektion: Nicht zu weit vorausplanen! Klingt komisch, ist aber so.

Es ist schwer sinnvoll abzuschätzen, wie sich Anforderungen und Code in Zukunft entwickeln. Es gibt einige Praktiken, die den Code robuster machen, aber viel genauer zu planen hat oft den gegenteiligen Effekt und erzeugt weitere Arbeit statt welche zu sparen. In diesem Fall wurde `capacity` vorsorglich zu `Double` gemacht, obwohl es keine gegenwärtige Anforderung dafür gab.

Entwickler sagen dazu meist [KISS](https://en.wikipedia.org/wiki/KISS_principle), wobei sie sich selbst in das letzte S mit einschließen.
