### ISSUE TITLE
Write Output CSV 

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#57]
Nach funktionierendem Einlesen einer CSV Datei soll nun das Ergebnis in eine andere CSV Datei geschrieben werden können

**Comment by nipafx** [comment]
Ich hab mal den Titel umbenannt. Als "parsen" bezeichnet man eine Zeichenkette in irgendwas sinnvolleres umzuwandelnt.

Mir ist außerdem aufgefallen, dass ihr die Issues relativ spät erstellt habt. Bitte macht das das nächste Mal direkt nach dem Release der vorherigen Version.

**Comment by jwustmann** [comment]
Machen wir gerne, allerdings ist es beim bearbeiten der ursprünglichen und früh erstellten Issues zu Teillösungen gekommen, deren fehlende Teile eigene Issues als Gedächtnisstütze erhalten haben

**Comment by nipafx** [comment]
Nicht, dass ihr mich falsch versteht: Issues teilweise zu lösen und für den Rest neue anzulegen ist vollkommen in Ordnung. Nur sollte am Anfang eines Meilensteins alles abgedeckt sein, damit ihr euren Fortschritt einschätzen könnt.
