### ISSUE TITLE
Fahrtberichtsfunktion für Autos

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#59]
Issue für @nicolaiparlog 's Vorhaben - ist wohl unter gegangen.

Es hieß in PullRequest #55
> Die Information ob ein Fahrzeug gefahren ist oder nicht, sollte besser am Fahrzeug vermerkt werden. Das passt sowohl konzeptionell ("Fahrzeug weiß, was es getan hat") als auch vom Code (die Fahrzeuge enthalten alle Informationen, die nötig sind, um sie zu schreiben).
   
> Werde gleich ein Issue dazu aufmachen.

**Comment by dbaumy** [comment]
Damit die Fahrzeug die Information beommen ob sie gefahren sind, kann ein weiterer Parameter, etwa namens `hasDriven` vom Typ `Boolean` hinzugefügt werden , der zu Beginn `false` gesetzt wird. Die Funktion `Scenario` kann dann den Wert auf `true` setzten wenn das Fahrzeug bewegt wurde.
