### ISSUE TITLE
Softwarelizenz in einer neuen Textdatei formulieren und in der README dokumentieren

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#6]
Unser Projekt braucht noch eine Lizenz. Darin sollen Nutzungsrechte, Schutz und Übertragbarkeit geregelt werden. Hierfür ist eine neue Textdatei anzulegen mit der Lizenz als Inhalt.

Da wir bisher keine Erfahrungen mit Softwarelizenzen haben, ist auch Bestandteil dieser Issue, wichtige Informationen einzuholen und anhand diesen eine Lizenz zu erstellen.

In der [README](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md "Link zu README des Projektes") ist auf die Lizenz zu verweisen.

**Comment by nipafx** [comment]
Ihr habt schon mal [sowas ähnliches](https://github.com/nicolaiparlog/energy-model/issues/2) gemacht. Jetzt könnt ihr vielleicht einen Schritt weiter gehen und euch näher damit beschäftigen:

* [Open source for absolute beginners](http://oss-watch.ac.uk/resources/beginners)
* [Open-Source Licensing For Dummies](http://www.binpress.com/blog/2013/06/21/open-source-licensing-for-dummies/).
* [An Introduction to Open-source Licenses](https://www.sitepoint.com/introduction-to-open-source-licenses/)

**Comment by RF-Buerky** [comment]
Ich denke bei der Lizenz können wir uns kurz fassen. Unser Projekt ist unbedeutend für die Welt, wir machen nichts großartiges. Daher schlage ich als Lizenz jene vor, die vom [Massachusetts Institute of Technology - MIT](https://de.wikipedia.org/wiki/Massachusetts_Institute_of_Technology "Link zum Wikipedia-Artikel des MIT") stammt. 

Bei dieser Lizenz kann jeder alles mit unserem Code machen, solange man auf uns als Schöpfer verweist. Zudem sichern wir uns gegen Verbindlichkeiten ab, falls etwas schief geht wegen unserem Code.

Die MIT-Lizenz selbst steht jedem frei und kann auch für den eigenen Gebrauch modifiziert werden. Der Text der Lizenz wie auch eine Übersetzung ins Deutsche könnt ihr auch auf dem [Wikipedia-Artikel](https://de.wikipedia.org/wiki/MIT-Lizenz "Link zum Wikipedia-Artikel zu MIT-Lizenz") ansehen.

Mit nem Thubs up könnt ihr mir einfach zustimmen diese Lizenz zu übernehmen. Dann werde ich die Datei anlegen.
