### ISSUE TITLE
Fragen klären zu Aufgabenstellung von Block 3

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#64]
In der Aufgabenstellung von Block 3 heißt es:
> cover an entire day by simulating 24 steps in a row:
> cars now need to know for each of the 24 hours whether they want to drive or not

Und noch:
> extend CSV input/output to match the new requirements and results:
> extend input to include for each hour whether a car wants to drive

Der Input für Block 3 ist also auch über eine CSV-Datei zu erhalten. Dann wäre doch für jedes einzelne Vehicle eine CSV-Datei zu erstellen, die die 24 Stunden auflistet, und ich welcher von diesen `wannaDrive = true` ist? Habe keine Idee wie all diese Informationen für mehrere Vehicles in eine CSV-Datei können.

Eine Beispiel-Datei könnte dann so aussehen:
> Dateiname sei: Car_7.csv
> // Aus dem Dateinahmen erhält man die Info, dass es ein Car ist und die Id 7 ist
> // Inhalt der Datei:
> hour,wannaDrive
> 0,true
> 1,true
> 2,true
> 3,false
> 4,false
> 5,true
>...

Was meint der Auftraggeber dazu? @nicolaiparlog

**Comment by jwustmann** [comment]
Für jedes Auto eine Datei? Das halte ich für sehr unübersichtlich.

Mein Vorschlag wäre eine Datei wie bisher. Wir können zusätzliche Spalten einfügen aus denen dann die Autos erstellt werden. Die Klasse `Vehicle` sähe dann so aus:
`class Vehicle(val id : Int, 
val wannaDriveHour1 : Boolean, 
val wannaDriveHour2 : Boolean,
val wannaDriveHour3 : Boolean,
val wannaDriveHour4 : Boolean,
...
val wannaDriveHour24 : Boolean,
var delayed : Boolean = false)`

Die `delayed` Drivelog Geschichte müssten wir aber anders aufbauen, sonst brauchen wir auch für jede Stunde einen Boolean.

Eleganter fände ich aber, wenn in einer CSV einfach die Stunden* (1,2,3,4,7,8,9,12, ...)eingelesen werden können, in denen das Auto fahren will und diese werden an eine `MutableList<Int>` namens Fahrplan in `vehicle` (Übersetzung wird notwendig sein) übergeben. Diese Liste können wir dann mit neuen Funktionen weiter verarbeiten. Das schöne daran ist, dass wenn man die Referenzstunde festlegt man beliebig viele tage in den Fahrplan integrieren kann (z.B. Stunde 25) wäre die erste Stunde des nächsten Tages; ist zwar nicht gefordert, aber erscheint mir aber praktisch, da mit quasi keinem Mehraufwand eine große Skalierung möglich ist.

*Wir müssen dann aber schauen, dass es keine Probleme mit dem Parser gibt, falls die Fahrpläne unterschiedlich lang sind; in diesem Fall müsste zumindest die CSV 24 Booleans enthalten, die wir dann normiert einlesen können. Ich bin aber in jedem Fall dafür, eine Fahrplan Liste im Auto zu haben, denn die ist meiner Meinung nach viel praktischer handhabbar als 24 Attribute, die z.B. nicht einfach in einer Schleife abgerufen werden können.

**Comment by RF-Buerky** [comment]
Ja, Liste mit Fahrplan im Fahrzeug ist gut.

Wenn man in der CSV nur die Stunden angeben würde wo es fährt wäre es angenehm kürzer. Denke auch dass da aber der Parser Probleme bekommt weil die Spaltenanzahl dann verschieden ist.

**Comment by nipafx** [comment]
Ich bin mir gar nicht sicher, ob die Spaltenzahl immer gleich sein muss, es wäre aber nicht unwahrscheinlich. Aber man muss zum Separieren der Stunden ja kein Komma nehmen. Was spricht dagegen:

    Car, Hours
    1, 6/7/8

Wenn euch das Komme ganz toll gefällt, kann man das auch verwenden, und mit `"` (meine ich) dafür sorgen, dass es gemeinsam geparst wird:

    Car, Hours
    1, "6, 7, 8"

Ich denke also schon, dass nur eine Datei nötig ist.

> Eleganter fände ich aber, wenn in einer CSV einfach die Stunden* (1,2,3,4,7,8,9,12, ...)eingelesen werden können, in denen das Auto fahren will und diese werden an eine `MutableList<Int>` namens Fahrplan in `vehicle` (Übersetzung wird notwendig sein) übergeben. Diese Liste können wir dann mit neuen Funktionen weiter verarbeiten.

:+1:

@RF-Buerky , @jwustmann, @dbaumy Es gibt drei technische Issues, die man einigermaßen parallel bearbeiten kann (#65, #66, #67). Teilt euch bitte rechtzeitig auf (und dann assigned euch), damit niemand leer ausgeht.

**Comment by jwustmann** [comment]
An dem Punkt möchte ich noch kurz  anmerken, dass auch @FelixWerle zum Team gehört und durch erstellen der issues und offline Leistungen einen enorm wichtigen Beitrag zu dem Erfolg der Gruppe leistet.

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nipafx** [comment]
> offline Leistungen

I see what you're doing there...

**Comment by RF-Buerky** [comment]
Diese Sache wäre dann durch den Merge von PullRequest #78  auch abgeschlossen.

**Comment by RF-Buerky** [comment]
Diese Sache wäre dann durch den Merge von PullRequest #78  auch abgeschlossen.

**Comment by jwustmann** [comment]
@nicolaiparlog 
Frage zur Aufgabenstellung:

> if a car gets delayed it can not “fulfill” it’s desire to drive, meaning it has to try to drive again in the next step (small example: a car wants to drive in steps 8 and 9 but gets delayed in 9; now it also wants to drive in step 10)

Wie sieht es aus, wenn ein Auto in 8 und 9 fahren will und in 8 verspätet wird? Wird dann auch in 10 gefahren?

**Comment by RF-Buerky** [comment]
Denke ja

**Comment by jwustmann** [comment]
dann ist das ganze wirklich ekelhaft...

**Comment by nipafx** [comment]
Wenn du zwei Stunden fahren musst, um anzukommen und eine Stunde im Stau stehst, wie viel Stunden hast du dann noch vor dir? :smiley:

Zum Thema ekelhaft: Versuch das Problem im Kleinen zu lösen. Das Auto weiß wann es fahren will und sollte jede Stunde danach gefragt werden. Zu jeder Stunde will es fahren, wenn...

* es eigentlich sowieso zu dieser Stunde fahren will
* wenn es in der Vergangenheit verspätet war und die Verspätung noch nicht abgebaut hat (mmh, sieht so aus als müsste es sich die Verspätung merken)

Es ist besser diese Logik in jedes Auto zu bauen statt an eine Stelle für alle zu entscheiden.

**Comment by RF-Buerky** [comment]
Ist es gemäß der aktuellen Aufgabenstellung nicht so, dass ein einmal entstandener Stau sich niemals wieder auflößt?

Die Kapazität sei 5. Im Zeitschritt 9 fahren 6 Autos, sie wollen eigentlich nur in Zeitschritt 9 fahren -> 6 werden verspätet -> 6 wollen in 10 weiter fahren -> 6 werden verspätet -> 6 wollen in 11 weiter fahren ....

bis in die Unendlichkeit und noch viel weiter.

Das kam mir gerade beim schreiben von Tests. Nur schade ist, dass der Code diesen ewigen Stau (noch) nicht bietet. Korrekt wäre er aber?

**Comment by RF-Buerky** [comment]
Wenn das so sein soll ist glaube ich dort der Fehler:
Klasse `Vehicle` , Zeilen 24 bis 30
>   fun driveAtHour(timestep: Int) {
        // if the vehicle wanted to drive, it is still as delayed as before
        // (otherwise it just gained an hour, thus reducing delay)
        if (!wannaDriveInHours.contains(timestep)) {
            delay -= 1
        }
    }


Hier müsste aber wird nirgens die Liste wannaDriveInHours erweitert. So müsst es, denke ich:
>   fun driveAtHour(timestep: Int) {
        // if the vehicle wanted to drive, it is still as delayed as before
        // (otherwise it just gained an hour, thus reducing delay)
        if (!wannaDriveInHours.contains(timestep)) {
            wannaDriveInHours.add(timestep + 1)
            delay -= 1
        }
    }

Oder ist dieser Impact auf wannaDrive durch einen Stau schon sonst irgendwo eingebunden?

**Comment by RF-Buerky** [comment]
Ja glaube habe einen Fehler gefunden. Der Impact auf die Liste `wannaDriveInHours` bei einem Stau war nirgens eingebunden. Wenn in Stunde 8 das Vehicle delayed wird, kommt die Stunde 9 in die wannaDrive-Liste hinzu.

Denke diese Sache kann man gut in die Funktion von Vehicle: `getDelayedAtHour(timestep : Int)` einbauen.

Aktuelle Version dieser Funktion:
>   fun getDelayedAtHour(timestep: Int) {
        // if the vehicle wanted to drive, its delay increased
       // (otherwise it just waited an hour, not reducing its delay)
        if (wannaDriveInHours.contains(timestep)) {
            delay += 1
            this.delayedInHours.add(timestep)
            this.delayedInHours.sort()
        }
    }


Version mit der Anpassung:
>    fun getDelayedAtHour(timestep: Int) {
        // if the vehicle wanted to drive, its delay increased
        // (otherwise it just waited an hour, not reducing its delay)
        if (wannaDriveInHours.contains(timestep)) {
            delay += 1
            this.delayedInHours.add(timestep)
            this.delayedInHours.sort()
            this.wannaDriveInHours.add(timestep + 1)
        }
    }


Oder ist sowas schon irgendwo drin und ich sehe es nicht?

**Comment by RF-Buerky** [comment]
Nach dieser Anpassung tritt ein, dass sich einmal dagewesene Staus niemals auflösen. Genauso wollen es die Tests in PullRequest #83 .

**Comment by nipafx** [comment]
> Oder ist sowas schon irgendwo drin und ich sehe es nicht?

Ja, in `delay`. Die Kommentare erklären auch ein bisschen, wie das funktioniert.

**Comment by RF-Buerky** [comment]
Ja das Attribut `delay` gibt es schon. Sehe aber nichts wo in Abhängigkeit von dem Zustand von `delay` ein `Vehicle` weitere `timesteps` in `wannaDriveInHours` erhält.

**Comment by nipafx** [comment]
Erhält es nicht, das ist ja genau der Trick. Statt die Liste der Fahrwünsche zu verändern (Jans Lösung war kompliziert, deine hat zu doppelten Stunden in der Liste geführt), prüfen wir einfach ob noch Verspätung abzubauen ist:

```kotlin
fun vehicleWantsToDriveAt(timestep :Int):Boolean{
    // the vehicle wants to drive if its drive plan says so
    // or if it got previously delayed
    return wannaDriveInHours.contains(timestep) || delay > 0
}
```

So bauen wir `delay` auf, wenn es zu Verspätungen kommt und wollen so lange fahren bis er wieder auf Null ist.

**Comment by RF-Buerky** [comment]
Hmm okay. Glaube habs kapiert.

und hier ist dann der Aufruf davon in RoadNetwork:
![grafik](https://user-images.githubusercontent.com/28202401/29117119-5730ae34-7cfd-11e7-92e6-ee3dd0dc0b7c.png)

**Comment by nipafx** [comment]
Ja.

**Comment by RF-Buerky** [comment]
Dann sei soweit alles geklärt.
