### ISSUE TITLE
Zufallsentscheidung für jedes Auto

### ISSUE THREAD

**Issue by FelixWerle** [RF-Buerky/BBFW-Project#65]
Die Entscheidung ob ein Fahrzeug fahren kann oder sich verspätet, soll zufällig erfolgen. Die Wahrscheinlichkeit, dass ein Fahrzeug sich verspätet, hängt davon ab,  wie viele Autos sich auf der Straße befinden, verglichen mit der gesamten Kapazität des Straßennetzes.

- weniger als **50%** der Kapazität genutzt: **5 %** Wahrscheinlichkeit der Verspätung
- weniger als **70%** der Kapazität genutzt: **10%** Wahrscheinlichkeit der Verspätung
- weniger als **90%** der Kapazität genutzt: **20%** Wahrscheinlichkeit der Verspätung
- weniger als **110%** der Kapazität genutzt: **30%** Wahrscheinlichkeit der Verspätung
- weniger als **125%** der Kapazität genutzt: **50%** Wahrscheinlichkeit der Verspätung
- weniger als **150%** der Kapazität genutzt: **70%** Wahrscheinlichkeit der Verspätung
- **über** **150%** der Kapazität  genutzt:  **90%** Wahrscheinlichkeit der Verspätung

**Comment by RF-Buerky** [comment]
Wie siehts denn hier aus @dbaumy , die Ideen sprudeln?
