### ISSUE TITLE
Simulation eines Tages

### ISSUE THREAD

**Issue by FelixWerle** [RF-Buerky/BBFW-Project#66]
Der gesamte Tag soll dargestellt werden, indem 24 Stufen nacheinander simuliert werden:

- Jedes Fahrzeug muss jede der 24 Stunden wissen, ob es fahren möchte oder nicht
- Wenn ein Fahrzeug verzögert wird kann es seine Funktion des ,,Fahrens" nicht erfüllen. Dies bedeutet es 
  muss in der nächsten Stufe fahren  (Beispiel: ein Fahrzeug möchte in den Stufen `8` und `9` fahren wird aber in Stufe `9 `aufgehalten, jetzt möchte es auch in Stufe `10` fahren
- Erweitern Sie die Ergebnisverfolgung, indem Sie sicherstellen, dass jedes Auto für jeden Schritt weiß, ob es fahren könnte oder verzögert wurde
- Aktualisieren Sie die `scenario` Funktion um die neuen Bedingungen

**Comment by RF-Buerky** [comment]
Teilweise gelößt durch PullRequest #79 . Die Tests werden in einer neuen Issue behandelt.
