### ISSUE TITLE
Code verbessern

### ISSUE THREAD

**Issue by nipafx** [RF-Buerky/BBFW-Project#73]
Ich gucke mir gerade den Code an und schreibe hier meine Gedanken dazu auf. Ich denke ihr solltet diese Details ändern, aber ich schreibe es euch nicht vor. Guckt euch das einfach an und schaut ob euch die Alternative gefällt.

Zu `Main`:

* es könnte zwei Methoden geben, die beide keine Parameter hätten:
    * `simulateCsvInput`: lädt aus CSV, simuliert, schreibt in CSV
    * `simulateFixedScenario`: erstellt einen Stapel Fahrzeuge und simuliert damit
* `main` könnte dann eine beliebige davon aufrufen, so das man einfach zwischen den beiden wechseln kann

Zu `Vehicle`:

* das Feld `delayed` ist so deklariert, dass man es beim Erstellen setzen kann - das gibt nicht so richtig Sinn. Warum nicht ein einfaches Feld `delayed` so ähnlich wie [hier](https://github.com/nicolaiparlog/energy-model/blob/master/src/main/kotlin/org/codefx/demo/bingen/bank/Account.kt#L13-L14)?
* die Methode `delayed` gibt ein neues Fahrzeug zurück. Das habe ich auch gelegentlich gemacht, aber dann handelte es sich um "Values", d.h. unveränderbare Dinge wie Geld oder Energie. Das Auto soll ja einen veränderlichen Zustand haben (gefahren oder nicht; ist also eine "Entity"), d.h. es sollte eher kein neues erstellt werden. Statt dessen kann man einfach das neue Feld `delayed` auf `true` setzen.
* alle Fahrezeuge, die fahren wollen, dürfen das auch; insofern verstehe ich den Sinn von `hasDriven` nicht so richtig

Zu `RoadNetwork`:

* Methoden machen etwas und ihre Namen sollten deswegen üblicherweise Verben sein - `scenario` verstößt besonders stark dagegen. Warum nicht `simulateTraffic` oder so?
* `gatherPlansToDrive` sammelt alle Fahrzeuge, die fahren wollen, in zwei Listen: `gatheredPlansToDrive`, die sie zurückgibt, und `vehiclesPlanningToDrive`, ein Feld, was nicht gelesen wird - ich glaube die letzte kann weg
* ganz ähnlich macht es `calculateDemand` mit `capacityDemand` und `capacityLoadByInterests`
* ganz ähnlich macht es `scenario` mit `vehiclesDriving` und `vehiclesDrove`
* warum gibt `scenario` eine Liste zurück? Wenn die bei Beginn der Simulation erstellten Fahrzeuge vermerkt bekommen, ob sie gefahren sind oder nicht, kann man diesen Zustand von außen ablesen - dafür muss man hier nichts zurückgeben

Damit hier nicht nur Negatives steht: Ihr macht das insgesamt echt gut und mir macht euer Fortschritt Spaß. Die Tests sind auch gut durchdacht und decken viele wichtige Fälle ab. 👍

**Comment by jwustmann** [comment]
Die unnötigen/redundanten Dinge können gerne entfernt werden.

Aufgabenstellung:
 

> write a scenario function that simulates a `scenario` with about a dozen cars

Da im OLAT das wort scenario unterlegt ist, quasi als Code formatiert, haben wir angenommen, dass dieser Name zwingend verwendet werden soll, damit klar ist, welche unserer Funktionen die Funktion aus der Aufgabenstellung abbildet. Der "Verstoß" an sich ist uns dank unserer intensiven und hochwertigen Ausbildung dieses und letztes Semester selbstredend aufgefallen. 😄 

Mir macht die Entwicklung tatsächlich auch Spaß 👍

**Comment by nipafx** [comment]
Ouch. Richtig, das ist auf meinem Mist gewachsen. Allerdings meinte ich damit eine Funktion in `Main`, die ein Scenario zusammenstellt und damit die Simulation aufruft. Macht es ein bisshen aber nicht wesentlich besser...
