### ISSUE TITLE
Fehlendes Teil im Output: DroveWithoutDelay einfügen

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#84]
Eine Sache wurde noch nicht in den Output aufgenommen. Die Vorgabe lautet:
>extend CSV input/output to match the new requirements and results:

>    extend input to include for each hour whether a car wants to drive
>    extend output to include for each hour whether the car drove or was delayed

Je nachdem wie man das versteht ist vielleicht außer der Ausgabe von delayed-Stunden auch eine Ausgabe von nicht-delayed-Stunden gefordert. Bisher gibt es nur die delayed-Stunden in der Ausgabe.

Ich denke man sollte dies noch einfügen.

**Comment by nipafx** [comment]
Ja, stimmt. Da fehlt eine weitere Spalte, die "drives" festhält.
