### ISSUE TITLE
Tests aktualisieren

### ISSUE THREAD

**Issue by jwustmann** [RF-Buerky/BBFW-Project#95]
Wie bei den vorherigen Versionen wird das Tests schreiben wohl besser wieder in einen separaten Issue verlegt.

**Comment by RF-Buerky** [comment]
Ich fang mal an ein paar Tests zu schreiben. Der Plan ist nicht dass ich die Tests alle schreibe, ihr könnt ja alle im Chat viele Tests einstellen die man dann einfügt.
