### ISSUE TITLE
Gucken wie es bei den anderen aussieht und freuen

### ISSUE THREAD

**Issue by RF-Buerky** [RF-Buerky/BBFW-Project#97]
Ein Rundumblick wie es bei den anderen Gruppen aussieht ist interessant.

**Comment by RF-Buerky** [comment]
Charge 1
![grafik](https://user-images.githubusercontent.com/28202401/29211261-576ad694-7e98-11e7-93c8-7b27af50f5c9.png)

Alle zwischen 0 und 1 Release

**Comment by RF-Buerky** [comment]
Charge 2
![grafik](https://user-images.githubusercontent.com/28202401/29211327-ac07dd6e-7e98-11e7-93ef-7cc58ff00a16.png)

Wir sind die einzige Gruppe die bisher Release 3.0 gemacht hat.

Der Aufgabenblock 4.0 erscheint vergleichsweise klein, den packen wir gewisse bis Sonntag.

**Comment by RF-Buerky** [comment]
@nicolaiparlog 
Bekommen wir noch einen Bonus weil theoretisch zu jeder Zeit alle Gruppen von uns hätten abgucken können? 😅 😅 😅

**Comment by nipafx** [comment]
Warum? Abgucken ist Herz und Seele jeder guten Programmierarbeit. Anderleuts Lösungen zu recherchieren und im eigenen Kontext anzuwenden ist eine sehr wichtige Fähigkeit. Für das Gegenteil gibt es sogar [ein Meme](https://en.wikipedia.org/wiki/Not_invented_here). Wenn überhaupt sollte ich allen was abziehen, die einfach alles selber gemacht haben... 😝

**Comment by RF-Buerky** [comment]
Interessant, nie von gehört 🎓 

![too-busy1](https://user-images.githubusercontent.com/28202401/29242286-5aa5b0ca-7f8a-11e7-9531-0c37eeb69168.png)

![nih-syndrome](https://user-images.githubusercontent.com/28202401/29242246-aef20e68-7f89-11e7-85ad-80eaf8a24543.png)

**Comment by nipafx** [comment]
😹

**Comment by RF-Buerky** [comment]
Es geht dem Ende entgegen. Da wird die Issue mal beseitigt.

**Comment by RF-Buerky** [comment]
Wir haben einen Maulwurf 😄 
Es wird nicht nur geguckt, es wird geforked
![grafik](https://user-images.githubusercontent.com/28202401/29245281-9839ece4-7fd5-11e7-94b8-9f97c04a4090.png)

**Comment by RF-Buerky** [comment]
Wir haben einen Maulwurf 😄 
Es wird nicht nur geguckt, es wird geforked
![grafik](https://user-images.githubusercontent.com/28202401/29245281-9839ece4-7fd5-11e7-94b8-9f97c04a4090.png)

**Comment by jwustmann** [comment]
Dreist :D

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RF-Buerky** [comment]
Charge 1:
![grafik](https://user-images.githubusercontent.com/28202401/29251095-951047b4-804f-11e7-8403-fb553283e03b.png)

Charge 2:
![grafik](https://user-images.githubusercontent.com/28202401/29251093-78eb4976-804f-11e7-94a8-0721a1bc0102.png)

Charge 3:
![grafik](https://user-images.githubusercontent.com/28202401/29251101-b9dbe5a8-804f-11e7-83dc-32091808ef07.png)

###### Die Nachricht wurd nachträglich um nicht nette Äußerungen gekürzt.

**Comment by RF-Buerky** [comment]
###### Die Nachricht wurde nachträglich um nicht nette Äußerungen gekürzt.

**Comment by nipafx** [comment]
@RF-Buerky, ich weiß deine Neugier zu schätzen, aber ich bitte dich, hier keine anderen Teams anzuschwärzen - egal ob es berechtigt ist oder nicht. Ich werde mir alle Projekte anschauen und dabei wird mir sowas sicherlich auffallen und zu entsprechenden Konsequenzen führen.
